title = "COMIC-POP"
description = "A vibrant, action-oriented design for graphic and expressive content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
