title = "SOFT-DECK"
description = "A comprehensive, tactile neumorphic deck design for structured information."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
