title = "LIGHT-BOX"
description = "A dark, focused design for high-contrast image and research analysis."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
