title = "VINYL-RECORD"
description = "A nostalgic, music-inspired design for high-fidelity and groove-focused content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
