title = "SOAP"
description = "A clean, minimalist neumorphic design for pure and essential content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
