title = "TYPEWRITER-KEY"
description = "A mechanical, high-depth design for input-focused and industrial content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
