title = "OMNIBUS"
description = "A comprehensive, collection-focused design for high-variety content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
