title = "SLIDE-PROJECTOR"
description = "A dark, cycle-focused design for high-impact visual analysis and storytelling."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
