title = "MANGA-PANEL"
description = "A structured, ink-inspired design for sequential and graphic content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
