title = "MUSIC-BOX"
description = "A nostalgic, wooden-inspired design for melodic and mechanical content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
