title = "SINGLE-STROKE"
description = "A minimalist, line-focused design for high-purity content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
