title = "LEAD-TYPE"
description = "A solid, lead-inspired design for foundational and printing content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
