title = "BROADSHEET-MAG"
description = "A massive, newspaper-inspired design for high-volume and authoritative content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
