title = "NEU-FOLIO"
description = "A creative, neumorphic portfolio design for high-depth visual work."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
