title = "CANVAS-EASEL"
description = "A creative, artist-inspired design for portfolio and visual content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
