title = "MARGINALIA"
description = "An asymmetrical design focused on commentary and notes in the margins."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
