title = "STYLE-GUIDE"
description = "A structured, rules-inspired design for formal design systems and style documentation."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
