title = "ESSENCE"
description = "A minimalist, high-purity design for fundamental content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
