title = "SCIENCE-JOURNAL"
description = "A structured, academic design for scientific research and technical papers."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
