title = "CASSETTE-DECK"
description = "An analog, dark design for musical and nostalgic content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
