title = "Macro Snowflake"
description = "Geometric, icy, and perfectly symmetrical winter patterns."
base_url = "http://localhost:3000"

[plugins]
processors = ["markdown"]

[content.files]
allow_extensions = ["jpg", "jpeg", "png", "gif", "svg", "webp"]

[highlight]
enabled = true
theme = "atom-one-dark"
use_cdn = true

[[taxonomies]]
name = "tags"
feed = true

[markdown]
safe = false
lazy_loading = true

[extra]
author = "Winter Artist"
