title = "Anaglyph"
description = "A bold and elegant 3D anaglyph aesthetic utilizing stereoscopic cyan and red color channels."
base_url = "http://localhost:3000"
compile_sass = false
minify_html = true
default_language = "en"

[extra]
author = "Hwaro"
