title = "COMIC-GRID"
description = "A structured, panel-inspired design for systematic and graphic content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
