title = "DOODLE-SKETCH"
description = "A creative, hand-drawn design for artistic and sketch-focused content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
