title = "BOOKPLATE"
description = "An 'Ex Libris' inspired design for curated collections."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
