title = "Scarlet Nexus"
description = "A striking, crimson-infused dark template for elegant reading."
base_url = "/"

[highlight]
enabled = true
theme = "base16/monokai"

[feeds]
enabled = true
filename = "rss.xml"
