title = "GALLERY-EDITORIAL"
description = "A sophisticated, magazine-inspired design for high-quality visual narrative."
default_language = "en"
base_url = "https://example.com"
[taxonomies]
tags = "tags"
categories = "categories"
