title = "NEU-MONO"
description = "A monospaced, neumorphic design for technical and structured content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
