title = "Liquid"
description = "A fluid, gooey, sticky blob theme"
base_url = "http://localhost:3000"

[plugins]
processors = ["markdown"]

[content.files]
allow_extensions = ["jpg", "jpeg", "png", "gif", "svg", "webp"]

[highlight]
enabled = false

[pagination]
enabled = false

[[taxonomies]]
name = "tags"

[sitemap]
enabled = true

[feeds]
enabled = true
type = "rss"

[markdown]
safe = false
