title = "INSURGENT"
description = "A subversive, broken-grid design for unconventional content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
