title = "Holographic Glass"
description = "A unique, slick, dark-themed holographic glassmorphism design."
base_url = "http://localhost:3000"

[plugins]
processors = ["markdown"]

[content.files]
allow_extensions = ["jpg", "jpeg", "png", "gif", "svg", "webp"]

[highlight]
enabled = true
theme = "atom-one-dark"
use_cdn = true

[pagination]
enabled = false
per_page = 5

[[taxonomies]]
name = "tags"
feed = true
sitemap = false

[[taxonomies]]
name = "categories"

[feeds]
enabled = true
filename = "rss.xml"
