title = "SOFT-TOGGLE"
description = "A minimalist, neumorphic design focused on states and interaction."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
