title = "GLASS-TERRACE"
description = "A spacious, multi-column glassmorphic design for overlooking comprehensive content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
