title = "Depot"
description = "Logistics / Shipment Tracker Theme"
base_url = "http://localhost:3000"

[plugins]
processors = ["markdown"]

[content.files]
allow_extensions = ["jpg", "jpeg", "png", "gif", "svg", "webp"]

[highlight]
enabled = false

[pagination]
enabled = false

[[taxonomies]]
name = "tags"

[sitemap]
enabled = true

[robots]
enabled = true

[search]
enabled = false

[markdown]
safe = false