title = "PAROXYSM"
description = "A high-tension design focused on sudden outbursts of energy."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
