title = "GLASS-DECK"
description = "A card-based glassmorphic design for modular and structured content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
