title = "INDENT-UI"
description = "A recessed, high-depth design focused on structural hierarchy and form."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
