title = "INSTA-FEED"
description = "A modern, social-inspired design for high-frequency visual updates."
default_language = "en"
base_url = "https://example.com"
[taxonomies]
tags = "tags"
categories = "categories"
