title = "GALLERY-BRUTALIST"
description = "A raw, high-impact design for uncompromised visual and structural content."
default_language = "en"
base_url = "https://example.com"
[taxonomies]
tags = "tags"
categories = "categories"
