title = "SOFT-PRESS"
description = "A tactile, neumorphic-inspired design for soft and welcoming content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
