title = "RUBBER-HOSE"
description = "A bouncy, vintage-inspired design for lively and animated content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
