title = "EPISTOLARY"
description = "A letter-writing, handwritten design for personal communication."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
