title = "QUILL-PEN"
description = "An expressive, artist-inspired design for writing and traditional content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
