title = "Xeno Vortex"
description = "An elegant, glowing neo-futuristic blog"
base_url = "http://localhost:3000"

[[taxonomies]]
name = "tags"
[[taxonomies]]
name = "categories"

[plugins]
[highlight]
enabled = true
[search]
enabled = true