title = "Ultraviolet"
description = "A bold, creative, and elegant ultraviolet theme"
base_url = "http://localhost:3000"

[extra]
author = "Ultraviolet Studio"

[markdown]
highlight_code = true
highlight_theme = "css"
