base_url = "http://localhost:3000"
title = "Kintsugi"
description = "A bold, creative, and elegant design inspired by the Japanese art of repairing broken pottery with gold."
default_language = "en"

[extra]
author = "Hwaro"

[markdown]
highlight_code = false
