title = "Minifolio"
description = "An ultra-minimal single-page portfolio"
base_url = "http://localhost:3000"

[extra]
email = "hello@example.com"

[plugins]
processors = ["markdown"]

[content.files]
allow_extensions = ["jpg", "jpeg", "png", "gif", "svg", "webp"]

[highlight]
enabled = false

[pagination]
enabled = false

[sitemap]
enabled = false

[robots]
enabled = false

[feeds]
enabled = false

[markdown]
safe = false
lazy_loading = true
