title = "Luminous Symphony"
base_url = "http://localhost:3000"
description = "A cosmic glassmorphism experience."

[build]
drafts = false

[taxonomies]
enabled = true
categories = "categories"
tags = "tags"

[highlight]
enabled = true
theme = "dracula"
