title = "CARTOON-FLAT"
description = "A simple, flat-toned design for modern and energetic animated content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
