title = "JACKHAMMER"
description = "A heavy, industrial, and rhythmic design for high-impact innovation."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
