title = "Cyber Neo"
base_url = "http://localhost:3000"
description = "A futuristic, cyber-themed portfolio with glowing neon and glassmorphic elements."

[pagination]
enabled = true
per_page = 5

[[taxonomies]]
name = "tags"
feed = true

[[taxonomies]]
name = "categories"

[feeds]
enabled = true
type = "rss"
limit = 10
filename = "rss.xml"