title = "FASHION-SPREAD"
description = "A vibrant, stylish design for high-end fashion and lifestyle content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
