title = "Scientific Journal"
base_url = "http://localhost:3000"
compile_sass = false
minify_html = true
build_search_index = false

[extra]
author = "Dr. Jane Doe"
description = "Extremely detailed, grid-heavy, annotated scientific journal."
