title = "POLAROID-FRAME"
description = "A nostalgic, frame-inspired design for instant and snapshot content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
