title = "DOUGH-UI"
description = "An elastic, extreme-depth neumorphic design for soft and substantial content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
