title = "CARTOON-PASTEL"
description = "A soft, pastel-toned design for gentle and whimsical animated content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
