title = "MIST-PANEL"
description = "A light, ethereal glassmorphic design focused on soft diffusion and clarity."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
