title = "Chromatic Veil"
base_url = "http://localhost:3000"
description = "A breathtaking journey through vibrant colors and ethereal glass."

[pagination]
enabled = true
per_page = 5

[[taxonomies]]
name = "tags"
feed = true
