title = "INK-WELL"
description = "A deep, ink-inspired design for fluid and expressive content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
