title = "Magnetite"
description = "Docs for a self-hosted search server with typo tolerance and faceting"
base_url = "http://localhost:3000"

[plugins]
processors = ["markdown"]

[content.files]
allow_extensions = ["svg"]

[highlight]
enabled = true
mode = "client"
theme = "monokai"
use_cdn = true

[search]
enabled = true
format = "fuse_json"
fields = ["title", "content"]
filename = "search.json"

[pagination]
enabled = false

[[taxonomies]]
name = "tags"
feed = false

[sitemap]
enabled = true

[robots]
enabled = true

[feeds]
enabled = false

[og]
type = "article"
twitter_card = "summary_large_image"

[markdown]
safe = false
lazy_loading = true
