title = "STELE"
description = "A vertical, monolith design for significant and commemorative content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
