title = "VISCERAL"
description = "A raw, organic, and emotional design focused on instinct."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
