title = "PLASTER"
description = "A raw, architectural design focused on material honesty."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
