title = "PAPERBACK"
description = "A classic, mass-market book design for accessible content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
