title = "GLASS-VIAL"
description = "A delicate, vial-inspired glassmorphic design for pure and condensed content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
