title = "MASONRY-GRID"
description = "A dynamic, variable-height design for high-density visual and structural content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
