title = "Cloudnest"
description = "Cloud hosting SaaS landing page"
base_url = "http://localhost:3000"

[plugins]
processors = ["markdown"]

[content.files]
allow_extensions = ["jpg", "jpeg", "png", "gif", "svg", "webp"]

[highlight]
enabled = false
theme = "github"
use_cdn = false

[pagination]
enabled = false
per_page = 10

[[taxonomies]]
name = "tags"
feed = false

[sitemap]
enabled = true

[robots]
enabled = true

[feeds]
enabled = false

[markdown]
safe = true
lazy_loading = true
