title = "Lithograph"
description = "A bold, creative, and elegant lithograph print aesthetic."
base_url = "http://localhost:1111"

# The language code. Default is 'en'
default_language = "en"

# A list of glob patterns specifying the files to ignore in the `content` directory
ignored_content = []

compile_sass = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = false

[[taxonomies]]
name = "tags"
feed = true

[[taxonomies]]
name = "categories"
feed = true

[extra]
author = "Publisher"
