title = "Iridescent Oil"
description = "Swirling, multicolored oil-on-water textures for a psychedelic look."
base_url = "http://localhost:3000"

[plugins]
processors = ["markdown"]

[content.files]
allow_extensions = ["jpg", "jpeg", "png", "gif", "svg", "webp"]

[highlight]
enabled = false

[pagination]
enabled = false

[sitemap]
enabled = true

[robots]
enabled = true

[feeds]
enabled = true
type = "rss"
limit = 10
sections = ["posts"]

[markdown]
safe = false
lazy_loading = true
