title = "Terrazzo"
description = "A bold, creative, and elegant Terrazzo aesthetic"
base_url = "http://localhost:3000"
default_language = "en"
build_search_index = true

[extra]
author = "Hwaro"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
