title = "CORK-BOARD"
description = "A tactile, cork-inspired design for collaborative and informal content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
