title = "WEBTOON"
description = "A long-form, vertical scrolling design for visual narratives."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
