title = "WAX-SEAL"
description = "An official, authentic design for verified and secure content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
