title = "BAREBONE"
description = "A raw, skeletal design focused on essential structure."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
