title = "Command Center"
description = "Sophisticated and trendy CLI documentation example site"
base_url = "http://localhost:3000"

[plugins]
processors = ["markdown"]

[content.files]
allow_extensions = ["jpg", "jpeg", "png", "gif", "svg", "webp"]

[highlight]
enabled = true
theme = "tokyo-night-dark"
use_cdn = true

[search]
enabled = true
format = "fuse_json"
fields = ["title", "content"]

[markdown]
safe = false
emoji = false

[[taxonomies]]
name = "tags"
feed = true

[[taxonomies]]
name = "categories"

[[taxonomies]]
name = "authors"

[sitemap]
enabled = true

[feeds]
enabled = true
type = "rss"
limit = 10
