title = "WINTER-GLASS"
description = "A cool, frost-tinted glassmorphic design for quiet and still content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
