title = "CATECHISM"
description = "A structured, Q&A design for foundational knowledge."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
