title = "Electroplate"
description = "A bold, creative, and elegant design simulating electroplated metal."
base_url = "https://example.com"
compile_sass = false
minify_html = true
default_language = "en"

[extra]
author = "Hwaro"
