title = "BESTIARY"
description = "A medieval manuscript, illustrative design for mythological content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
