title = "CARTOON-RETRO"
description = "A nostalgic, vintage-inspired design for classic and origin-focused content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
