title = "ParallaxHeavy"
description = "Extreme Scroll Parallax Animation Theme"
base_url = "http://localhost:3000"

[plugins]
processors = ["markdown"]

[content.files]
allow_extensions = ["jpg", "jpeg", "png", "gif", "svg", "webp"]

[markdown]
safe = false
