title = "MEGAPHONE"
description = "A bold, directed design for loud and clear messaging."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
