title = "MOTION-COMIC"
description = "A dynamic, cinematic design for high-action and narrative comic content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
