title = "Silent Ash"
description = "A minimalist, sophisticated aesthetic inspired by silent ash."
base_url = "http://localhost:3000"

[plugins]
processors = ["markdown"]

[[taxonomies]]
name = "tags"
feed = true
sitemap = false

[[taxonomies]]
name = "categories"
paginate_by = 5

[[taxonomies]]
name = "authors"

[markdown]
safe = false
lazy_loading = false
emoji = false
