title = "TICKET-STUB"
description = "A nostalgic, ticket-inspired design for event-based and ephemeral content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
