title = "Ferrofluid"
base_url = "http://localhost:3000"
compile_sass = false
minify_html = true
build_search_index = false

[extra]
author = "Hwaro"
description = "A bold, elegant, and creative ferrofluid theme without gradients."
