title = "SEISMOGRAPH"
description = "A data-focused, line-art design for monitoring change."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
