title = "SYLLABARY"
description = "A phonetic-focused design for structural, sound-based content."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
