title = "RUPTURE"
description = "A broken-grid, textured design for destructive beauty."
default_language = "en"
base_url = "https://example.com"

[taxonomies]
tags = "tags"
categories = "categories"
