title = "Sgraffito"
description = "A bold, creative, and elegant design featuring a Sgraffito aesthetic."
base_url = "http://localhost:3000"

[markdown]
safe = false
emoji = false

[plugins]
processors = ["markdown"]

[search]
enabled = true
format = "fuse_json"

[sitemap]
enabled = true

[robots]
enabled = true

[llms]
enabled = true
