title = "Sgraffito"
description = "A bold, creative, and elegant design featuring a Sgraffito aesthetic."
base_url = "http://localhost:3000"
default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
author = "Hwaro Examples"
